# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

  config.vm.provision :shell, :path => "install.sh"

  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true

#  config.vm.provider "virtualbox" do |vb|
#    vb.cpus = 2
#    vb.memory = "1024"
#  end
  config.vm.define "worker1" do |c|
      c.vm.hostname = "worker1"
      c.vm.network "private_network", ip: "192.168.56.31"
      #, auto_config: false
      c.vm.network "forwarded_port", guest: 10250, host: 11250
      c.vm.network "forwarded_port", guest: 10255, host: 11255
  end

    config.vm.define "worker2" do |c|
      c.vm.hostname = "worker2"
      c.vm.network "private_network", ip: "192.168.56.32"
      #, auto_config: false
      c.vm.network "forwarded_port", guest: 10251, host: 11251
      c.vm.network "forwarded_port", guest: 10256, host: 11256
  end
  
end
